# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  config.vm.hostname = "cmws-elk"

  #config.vm.box = "./packer_checkmyws-elk_virtualbox.box"

  config.vm.box = "ubuntu/trusty64"

  config.vm.network "private_network", ip: "192.168.56.20"

  config.ssh.forward_agent = true
 
  config.vm.provider "virtualbox" do |vb|
    vb.customize ["modifyvm", :id, "--memory", "2048"]
  end
  
  config.vm.provision :file do |file|
    file.source      = './files'
    file.destination = '/home/vagrant/'
  end

  config.vm.provision "shell", path: "install.sh"

end
